version: "3.8"
services:
  epic-free-games:
    build: .
    container_name: epic-free-games
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - INTERVAL_MINUTES=10
    command: ["bash", "start.sh"]
    develop:
      watch:
        - path: .
          action: sync
          target: /app
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./Dockerfile
          action: rebuild